name: PYCORA
title: Pycora
description: Static Site Generator with Python - Fast, Minimal, Elegant
url: https://pycora.axcora.com
about_url: /pages/nyiblorong/about/
author: Axcora
twitter_username: https://www.axcora.com
image: /img/axcoranewlogored.webp
favicon: /img/axcoranewlogored.webp
